name: Build dummy discovery

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Build
        run: go tool task build-dummy-discovery
